version: "2.1"
services:
  mysql_db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gateway
    volumes:
      - ./src/main/resources/initDB:/docker-entrypoint-initdb.d
    networks:
      - gateways
networks:
  gateways:
    name: custom_gateways
