server:
  servlet:
    context-path: /gateways-api
springdoc:
  packages-to-scan: com.musala.gatewaysapi.controllers
  paths-to-match: /api/rest/**
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    root: info
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "httptrace,health,info"
  endpoint:
    httptrace:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  server:
    base-path: /actuator
musala:
  datasource:
    host: localhost
    port: 3306
    username: dev
    password: dev
gateways:
  security:
    name: KM57OfbQz0scHVBn
    password: 4wiAox57mJRoVyUx
    role: API_USER
spring:
  main:
    allow-bean-definition-overriding: true
  gson:
    exclude-fields-without-expose-annotation: true
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  datasource:
    url: jdbc:mysql://${musala.datasource.host}:${musala.datasource.port}/gateway
    username: ${musala.datasource.username}
    password: ${musala.datasource.password}
    validation-query: SELECT 1;
    hikari:
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 90000
      initialization-fail-timeout: -1
  jpa:
    open-in-view: true
  liquibase:
    databaseChangeLogTable: GATEWAYS_DATABASECHANGELOG
    databaseChangeLogLockTable: GATEWAYS_DATABASECHANGELOGLOCK
endpoint:
  security:
    user:
      name: ${gateways.security.name}
      password: ${gateways.security.password}
      role: ${gateways.security.role}
      management-context: ${management.server.base-path}